[package]
name = "agus-observer"
version = "0.1.0"
edition = "2021"

[dependencies]
agus-core-domain = { path = "../agus-core-domain" }
agus-ssh = { path = "../agus-ssh" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
chrono = "0.4"
